apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config-map
data:
  # property-like keys; each key maps to a simple value
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-dev.default.svc.cluster.local:5432/app_db
  API_URL_BOOK_ITEM: http://inventory-service.default.svc.cluster.local:8091/items/book
  API_URL_CANCEL_BOOKING: http://inventory-service.default.svc.cluster.local:8091/items/cancelBooking
  API_URL_CREATE_PAYMENT: http://billing-service.default.svc.cluster.local:8090/accounts/transactions/byClientId