apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    service: order-service  
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http-order