apiVersion: v1
kind: Service
metadata:
  name: person-service
  labels:
    service: person-service   
spec:
  selector:
    app: person
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http-person